apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: helm-repos
  namespace: flux-system
spec:
  interval: 5m
  path: ./apps/helm-repos
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-cluster
  targetNamespace: flux-system
