#apiVersion: kustomize.toolkit.fluxcd.io/v1
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: flux-cluster
  namespace: flux-system
spec:
  interval: 5m
  path: ./clusters/prod
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-cluster
  dependsOn: []

