# clusters/prod/kustomization.yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-cluster
  namespace: flux-system
spec:
  interval: 5m
  path: ./clusters/prod
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-cluster
  targetNamespace: flux-system
resources:
  - gitea.yaml
