# apps/gitea/kustomization.yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gitea
  namespace: flux-system
spec:
  interval: 5m
  path: ./apps/gitea
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-cluster
  targetNamespace: gitea
  dependsOn:
    - name: helm-repos
